app/urls.py
from django.urls import path

from .views import (
    homepage, 
    time_out, 
    delete, 
    category_page, 
    category_delete ,
    SignUpView,
    break_in,
    break_out,
    schedule_page,
    time_in
    )


app_name = "app"

urlpatterns = [
    path('', homepage, name="homepage"),
    path('time-out/<int:pk>/', time_out, name="time_out"),
    path('delete/<int:pk>/', delete, name="delete"),
    path('category/', category_page, name="category"),
    path('category-delete/<int:pk>/', category_delete, name="category_delete"),
    path('register/', SignUpView.as_view(), name="register"),
    path('break-out/<int:pk>/', break_out, name="break_out"),
    path('break-in/<int:pk>/', break_in, name="break_in"),
    path('schedule-page/', schedule_page, name="schedule_page"),
    path('time-in/<int:pk>/', time_in, name="time_in"),
]

tito_app/urls.py
"""tito_app URL Configuration
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include("app.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

app/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=255)

    def __str__(self):
        return self.category
    

class TimeInTimeOut(models.Model):
    status = (
        ('Time In', 'Time In'),
        ('Time Out', 'Time Out'),
        ('Break In', 'Break In'),
        ('Break Out', 'Break Out'),
    )
    date_created = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    shift_date = models.DateField(auto_now_add=False)
    time_in = models.TimeField(auto_now_add=False, blank=True, null=True)
    time_out = models.TimeField(auto_now_add=False,blank=True, null=True)
    break_in = models.TimeField(auto_now_add=False, blank=True, null=True)
    break_out = models.TimeField(auto_now_add=False,blank=True, null=True)
    total_hrs = models.DurationField(blank=True, null=True)
    status = models.CharField(max_length=255, blank=True, null=True)
    task = models.TextField(max_length=1000, blank=True, null=True)
     

    def __str__(self):
        return f"{self.category}" + " | " + f"{self.time_in}" + " | " + f"{self.time_out}" + " | " + f"{self.shift_date}"
    

app/forms.py
from django import forms

from .models import TimeInTimeOut, Category

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.DateInput):
    input_type = 'time'

class TimeInTimeOutForms(forms.ModelForm):
    class Meta:
        model = TimeInTimeOut
        fields = ['category','shift_date', 'time_in' , 'time_out',  'break_out','break_in', 'task']
        widgets = {
            'shift_date' : DateInput(),
            'time_in' : TimeInput(),
            'time_out' : TimeInput(),
            'break_in' : TimeInput(),
            'break_out' : TimeInput(),
        }

class CategoryForms(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

app/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from .models import TimeInTimeOut, Category
from .forms import TimeInTimeOutForms, CategoryForms
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
import speech_recognition as sr
import pyttsx3 

r = sr.Recognizer() 



@login_required
def homepage(request):
    template_name = "app/homepage.html"
    
    # """ Time In Form """
    form = TimeInTimeOutForms(request.POST or None)
    now = datetime.now()
    date_today = now.strftime("%B %d %Y") 
    time_now = now.strftime("%H:%M:%S") 

    if form.is_valid():
        
        form.save()
        messages.error(request, "Schedule Created")
        text = r.listen("Schedule created")
        
        return redirect("app:homepage")
    else:
        form = TimeInTimeOutForms(request.POST or None)

    # """ Time In List """
    date_today = now.strftime("%B %d %Y") 
    print(date_today)
    time_in_list = TimeInTimeOut.objects.filter(shift_date=now).order_by('shift_date')

    context = {
        'form': form,
        'time_in_list' : time_in_list,
        'date_today' : date_today,
    }
    return render(request, template_name, context)

@login_required
def schedule_page(request):
    template_name = "app/schedule_page.html"

    # """ Time In Form """
    form = TimeInTimeOutForms(request.POST or None)
    now = datetime.now()
    time_now = now.strftime("%H:%M:%S") 
    if form.is_valid():
        
        form.save()
        messages.error(request, "Schedule Created")
        text = "Schedule Created"
        engine = pyttsx3.init()
        engine.setProperty('rate', 170)
        engine.say(text) 
        engine.runAndWait()
        return redirect("app:schedule_page")
    else:
        form = TimeInTimeOutForms(request.POST or None)

    # """ Time In List """
    date_today = now.strftime("%B %d %Y") 
    print(date_today)
    time_in_list = TimeInTimeOut.objects.all().order_by('shift_date')

    context = {
        'form': form,
        'time_in_list' : time_in_list,
        'date_today' : date_today,
    }
    return render(request, template_name, context)

@login_required
def time_out(request, pk):
    now = datetime.now()
    time_now = now.strftime("%H:%M:%S")
    time_data = get_object_or_404(TimeInTimeOut, pk=pk)
    
    time_in_list = TimeInTimeOut.objects.all().order_by('-time_in')

    for i in time_in_list:

        date = i.date_created
        in_time = datetime.combine(date, i.time_in)
        total = now - in_time

    total_time = total
    print("Total",total_time)
    time_data.total_hrs = total_time
    time_data.time_out = time_now
    time_data.status = "Time Out"
    text = "Time Out"
    engine = pyttsx3.init()
    engine.setProperty('rate', 170)
    engine.say(text) 
    engine.runAndWait()
    time_data.save()
    messages.success(request, "Time Out")
    return redirect("app:homepage")

@login_required
def break_out(request, pk):
    now = datetime.now()
    time_now = now.strftime("%H:%M:%S")
    time_data = get_object_or_404(TimeInTimeOut, pk=pk)
    
    time_data.break_out = time_now
    time_data.status = 'Break Out'
    text = "Break Out"
    engine = pyttsx3.init()
    engine.setProperty('rate', 170)
    engine.say(text) 
    engine.runAndWait()
    time_data.save()
    messages.success(request, "On-Break")
    return redirect("app:homepage")

@login_required
def time_in(request, pk):
    now = datetime.now()
    time_now = now.strftime("%H:%M:%S")
    time_data = get_object_or_404(TimeInTimeOut, pk=pk)
    text = "Time In"
    engine = pyttsx3.init()
    engine.setProperty('rate', 170)
    engine.say(text) 
    engine.runAndWait()
    time_data.time_in = time_now
    time_data.status = 'Time In'
    time_data.save()
    messages.success(request, "Time In")
    return redirect("app:homepage")

@login_required
def break_in(request, pk):
    now = datetime.now()
    time_now = now.strftime("%H:%M:%S")
    time_data = get_object_or_404(TimeInTimeOut, pk=pk)
    
    time_data.break_in = time_now
    time_data.status = "Break In"
    text = "Break In"
    engine = pyttsx3.init()
    engine.setProperty('rate', 170)
    engine.say(text) 
    engine.runAndWait()
    time_data.save()
    messages.success(request, "Break In")
    return redirect("app:homepage")

@login_required
def delete(request, pk):

    time_data = get_object_or_404(TimeInTimeOut, pk=pk)

    time_data.delete()
    messages.success(request, "Data successfully deleted")
    text = "Data successfully deleted"
    engine = pyttsx3.init()
    engine.setProperty('rate', 170)
    engine.say(text) 
    engine.runAndWait()
    return redirect("app:schedule_page")
  

@login_required
def category_page(request):
    template_name = "app/category.html"

    category = Category.objects.all()

    form = CategoryForms(request.POST or None)

    if form.is_valid():
        form.save()
        messages.success(request, "Category created successfully")
        return redirect("app:category")
    else:
        form = CategoryForms(request.POST or None)

    context = {
        "category" : category,
        'form' : form
    }

    return render(request, template_name, context)

@login_required   
def category_delete(request, pk):

    category = get_object_or_404(Category, pk=pk)

    category.delete()
    messages.success(request, "Data successfully deleted")
    return redirect("app:category")

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

app/templates/app/category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% block extrastylesheet %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"> 
    <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet"> 
{% endblock extrastylesheet %}


<div class="container mt-3">
{% for message in messages %}
      <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{message}}
    </div>

{% endfor %} 

    <h3 style="color: white;">Time In Time Out Category</h3>
    <button type="button" class="btn btn-sm text-white mb-3" data-toggle="modal" data-target="#exampleModal" style="background-color: #1483fe;">
        Add Category 
    </button>

            
    <div class="card p-3" style="color: white; background-color: #131217; box-shadow:  0 8px 16px 0 rgb(20,131,254)">
        <table class="table table-sm table-borderless text-center" id="tito_table"  style="color: white; background-color: #131217;">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Category</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            
            <tbody>
            {% for list in category %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{list.category}}</td>
                    <td>
                        <a href={% url "app:category_delete" list.pk %} class="btn btn-danger btn-sm">
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            
        </table>
    </div>
    

</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Category</h5>
            <a href="{% url 'app:category' %}" class="close">
            <span aria-hidden="true">&times;</span>
            </a>
        </div>
        <form method="POST">
        {% csrf_token %}
            <div class="modal-body">
                {{form|crispy}}
            </div>
            <div class="modal-footer">
                <a href="{% url 'app:category' %}" class="btn btn-secondary btn-sm">Cancel</a>
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </div>
        </form>
    </div>
  </div>
</div>

<script>
function showTime(){
    var date = new Date();
    var h = date.getHours(); // 0 - 23
    var m = date.getMinutes(); // 0 - 59
    var s = date.getSeconds(); // 0 - 59
    var session = "AM";
    
    if(h == 0){
        h = 12;
    }
    
    if(h > 12){
        h = h - 12;
        session = "PM";
    }
    
    h = (h < 10) ? "0" + h : h;
    m = (m < 10) ? "0" + m : m;
    s = (s < 10) ? "0" + s : s;
    
    var time = h + ":" + m + ":" + s + " " + session;
    document.getElementById("clock").innerText = time;
    document.getElementById("clock").textContent = time;
    
    setTimeout(showTime, 1000);
    
}

showTime();

$(document).on('submit','#tito_form',function(e){
e.preventDefault();
$.ajax({
    type:'POST',
    url:'{% url "app:homepage" %}',
    data:
    {
        task:$("#category").val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
    },
    success:function(){
        startTimer()
        alert('Saved');
    }
    })
});

</script>

<script>
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 2000);
</script>
{% endblock %}

{% block tablescript %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>

<script>
    $(document).ready(function() {
        $('#tito_table').DataTable(
            {
                "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
                fixedHeader: true,
                "searching": false
            }
        );
        
    } );
</script>
{% endblock tablescript %}

app/templates/app/homepage.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
{% block extrastylesheet %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"> 
    <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet"> 
{% endblock extrastylesheet %}


<div class="container mt-3">
{% for message in messages %}
      <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{message}}
    </div>

{% endfor %} 
   <h3 style="color: white;">Time In Time Out System</h3>

            <form method="post" id="tito_form">
            {% csrf_token %}
                <table class="table table-borderless">
                    <thead  style="color: white;">
                        <tr>
                            <th>Category</th>
                            <th></th>
                            <th>Time</th>
                            <th>Time In</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                        <th scope="col">
                            <div class="form-group">
                                <select class="form-control form-control-sm" id="category" name="category">
                                    <option>Getaka Labs</option>
                                    <option>Quadralogix</option>
                                </select>
                            </div>
                        </th>
                        <th></th>
                        <th scope="col" >
                            <div id="clock" onload="showTime()" style="color: white;">
                                
                            </div>
                        </th>
                        <th scope="col">
                            <button class="btn btn-primary btn-sm"  >Time In</button>
                        </th>
                        </tr>
                    </tbody>
                    
                </table>
            </form>    
    <div class="card p-3" style="color: white; background-color: #131217;">
        <table class="table table-sm table-borderless text-center" id="tito_table"  style="color: white; background-color: #131217;">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date Created</th>
                    <th scope="col">Category</th>
                    <th scope="col">Time In</th>
                    <th scope="col">Time Out</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            
            <tbody>
            {% for list in time_in_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{list.date_created}}</td>
                    <td>{{list.category}}</td>
                    <td>{{list.time_in|default_if_none:""}}</td>
                    <td>
                        {% if list.time_out == None %}
                            <a href={% url "app:time_out" list.pk %} class="btn btn-danger btn-sm">Time Out</a>
                        {% else %}
                            {{list.time_out}}
                        {% endif %}
                    </td>
                    <td>
                        {% if list.time_out == None %}
                            <button type="button" class="btn btn-danger btn-sm" disabled>
                                <i class="far fa-trash-alt"></i>
                            </button>
                        {% else %}
                            <a href={% url "app:delete" list.pk %} class="btn btn-danger btn-sm">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            
        </table>
    </div>
    

</div>

<script>
function showTime(){
    var date = new Date();
    var h = date.getHours(); // 0 - 23
    var m = date.getMinutes(); // 0 - 59
    var s = date.getSeconds(); // 0 - 59
    var session = "AM";
    
    if(h == 0){
        h = 12;
    }
    
    if(h > 12){
        h = h - 12;
        session = "PM";
    }
    
    h = (h < 10) ? "0" + h : h;
    m = (m < 10) ? "0" + m : m;
    s = (s < 10) ? "0" + s : s;
    
    var time = h + ":" + m + ":" + s + " " + session;
    document.getElementById("clock").innerText = time;
    document.getElementById("clock").textContent = time;
    
    setTimeout(showTime, 1000);
    
}

showTime();

$(document).on('submit','#tito_form',function(e){
e.preventDefault();
$.ajax({
    type:'POST',
    url:'{% url "app:homepage" %}',
    data:
    {
        task:$("#category").val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
    },
    success:function(){
        startTimer()
        alert('Saved');
    }
    })
});

</script>

<script>
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 2000);
</script>
{% endblock %}

{% block tablescript %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>

<script>
    $(document).ready(function() {
        $('#tito_table').DataTable(
            {
                "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
                fixedHeader: true,
                "searching": false
            }
        );
        
    } );
</script>
{% endblock tablescript %}

app/templates/app/schedule_page.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load static %}


{% block content %}
{% block extrastylesheet %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet"> 
    <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css" rel="stylesheet"> 
{% endblock extrastylesheet %}


<div class="container-fluid mt-3">
{% for message in messages %}
      <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{message}}
    </div>

{% endfor %} 
   <h3 style="color: white;">Schedule</h3>

    <div id="clock" onload="showTime()" style="color: white;"></div>
    <br>
    <button type="button" class="btn btn-primary btn-sm mb-3" data-toggle="modal" data-target="#staticBackdrop">
        Create Schedule
    </button>  
    <a href="{% url 'app:category' %}" class="btn btn-success btn-sm mb-3">
        View Category
    </a>
    
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static"
     data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Schedule</h5>
                <a href="{% url 'app:schedule_page' %}" class="close">
                <span aria-hidden="true">&times;</span>
                </a>
            </div>
            <form method="POST">
            {% csrf_token %}
                <div class="modal-body">
                    {{form|crispy}}
                </div>
                <div class="modal-footer">
                    <a href="{% url 'app:schedule_page' %}" class="btn btn-secondary btn-sm">Cancel</a>
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                </div>
            </form>
        </div>
    </div>
    </div>
    <!-- End Modal -->

    <div class="card p-3" style="color: white; background-color: #131217; box-shadow:  0 8px 16px 0 rgb(20,131,254)">
        <table class="table table-sm table-borderless text-center" id="tito_table"  style="color: white; background-color: #131217;">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Shift Date</th>
                    <th scope="col">Category</th>
                    <th scope="col">Time In</th>
                    <th scope="col">Break Out</th>
                    <th scope="col">Break In</th>
                    <th scope="col">Time Out</th>
                    {% comment %} <th scope="col">Task</th> {% endcomment %}
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            
            <tbody>
            {% for list in time_in_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{list.shift_date}}</td>
                    <td>
                    {% if list.category == 'Getaka Labs' %}
                        <span class="badge badge-primary">{{list.category}}</span>
                    {% elif list.category == 'Quadralogix' %}
                        <span class="badge badge-danger">{{list.category}}</span>
                    {% endif %}
                    <span class="badge badge-info">{{list.category}}</span>
                    </td>
                    <td>{{list.time_in|default_if_none:""}}</td>
                    <td>
                    {% if list.break_out == None %}
                        <a href={% url "app:break_out" list.pk %} >
                            <span class="badge badge-warning">Break Out</span>
                        </a>
                    {% else %}
                        {{list.break_out}}
                    {% endif %}
                    </td>
                    <td>
                    {% if list.break_in == None %}
                            <a href={% url "app:break_in" list.pk %} >
                                <span class="badge badge-primary">Break In</span>
                            </a>
                        {% else %}
                            {{list.break_in}}
                        {% endif %}
                    </td>
                    <td>
                        {% if list.time_out == None  %}
                            <a href={% url "app:time_out" list.pk %} onclick="stop()">
                                <span class="badge badge-danger">Time Out</span>
                            </a>
                        {% else %}
                            {{list.time_out}}
                        {% endif %}
                    </td>
                    {% comment %} <td>
                        <div style="font-size: 12px;">
                            {{list.task|linebreaks}}
                        </div>
                    </td> {% endcomment %}
                    <td>
                        <span class="badge badge-pill badge-primary"> </span>
                        <span class="badge badge-pill badge-warning"> </span>
                        {% if list.status == 'Time Out' %}
                            <button class="btn btn-danger btn-sm">{{list.status}}</button>
                        {% else %}
                            {{list.status|default_if_none:"Not yet logged in"}}
                        {% endif %}
                        <span class="badge badge-pill badge-warning"> </span>
                        <span class="badge badge-pill badge-primary"> </span>
                    </td>
                    <td>
                        {% if list.time_out == None or list.break_out == None or list.break_in == None %}
                            <button type="button" class="btn btn-danger btn-sm" disabled>
                                <i class="far fa-trash-alt"></i>
                            </button>
                        {% else %}
                            <a href={% url "app:delete" list.pk %} class="btn btn-danger btn-sm">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        {% endif %}
                        
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            
        </table>
    </div>
    

</div>

<script>
var timer;
var startTime;

function start() {
  startTime = parseInt(localStorage.getItem('startTime') || Date.now());
  localStorage.setItem('startTime', startTime);
  timer = setInterval(clockTick, 100);
}

function stop() {
  clearInterval(timer);
}

function reset() {
  clearInterval(timer);
  localStorage.removeItem('startTime');
  document.getElementById('display-area').innerHTML = "00:00:00.000";
}

function clockTick() {
  var currentTime = Date.now(),
    timeElapsed = new Date(currentTime - startTime),
    hours = timeElapsed.getUTCHours(),
    mins = timeElapsed.getUTCMinutes(),
    secs = timeElapsed.getUTCSeconds(),
    ms = timeElapsed.getUTCMilliseconds(),
    display = document.getElementById("display-area");

  display.innerHTML =
    (hours > 9 ? hours : "0" + hours) + ":" +
    (mins > 9 ? mins : "0" + mins) + ":" +
    (secs > 9 ? secs : "0" + secs) + "." +
    (ms > 99 ? ms : ms > 9 ? "0" + ms : "00" + ms);
};

var stopBtn = document.getElementById('stop_btn');

stopBtn.addEventListener('click', function() {
  stop();
})

start();

</script>

<script>
function showTime(){
    var date = new Date();
    var h = date.getHours(); // 0 - 23
    var m = date.getMinutes(); // 0 - 59
    var s = date.getSeconds(); // 0 - 59
    var session = "AM";
    
    if(h == 0){
        h = 12;
    }
    
    if(h > 12){
        h = h - 12;
        session = "PM";
    }
    
    h = (h < 10) ? "0" + h : h;
    m = (m < 10) ? "0" + m : m;
    s = (s < 10) ? "0" + s : s;
    
    var time = h + ":" + m + ":" + s + " " + session;
    document.getElementById("clock").innerText = "Current Time : " + time;
    document.getElementById("clock").textContent = "Current Time : " + time;
    
    setTimeout(showTime, 1000);
    
}

showTime();
{% comment %} 
$(document).on('submit','#tito_form',function(e){
e.preventDefault();
$.ajax({
    type:'POST',
    url:'{% url "app:homepage" %}',
    data:
    {
        task:$("#category").val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
    },
    success:function(){
        startTimer()
        alert('Saved');
    }
    })
}); {% endcomment %}

</script>

<script>
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 2000);
</script>
{% endblock %}

{% block tablescript %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>

<script>
    $(document).ready(function() {
        $('#tito_table').DataTable(
            {
                "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
                fixedHeader: true,
                "searching": false
            }
        );
        
    } );
</script>
{% endblock tablescript %}

templates/navbar.html
<nav class="navbar shadow" style="height: 70px; background-color: #131217;">
  <span class="navbar-brand mb-0 h1 mr-auto" style="color: #1483fe;">
  <a href="{% url 'app:homepage' %}" class="navbar-brand">
      TITO | Time In Time Out
  </a>
  </span>

  <span class="navbar-text">
     <a href="{% url 'logout' %}" class="navbar-brand">
      Log out
    </a>
    </span>
</nav>